### PR TITLE
Add URI and string fields validation

### PR DESCRIPTION
**Pull request by sschiavoni**

### CODE REVIEW

**Comment by shakusa** [comment]
Would you mind throwing in the cap-validator -> cap-validator-hrd change to the validator's appengine-web.xml?

**Comment by sschiavoni** [comment]
@shakusa I already submitted the change for the App identifier at HEAD (https://github.com/google/cap-library/blob/master/validator/war/WEB-INF/appengine-web.xml). This change needs to be merged. Is this what you were referring to?

**Comment by sschiavoni** [comment]
@shakusa Concerning the weather.atom: yes, I'm going to rollback my rollback and make sure the file is identical to the one we have internally. I didn't realize that it was recently changed, and I didn't understand what was happening.

**Comment by sschiavoni** [comment]
@shakusa PTAL

**Comment by shakusa** [comment]
LGTM

Both comments are resolved.
Thanks!

**Pull request merged**
